// Generated by CoffeeScript 1.7.1
(function() {
  var TravelLayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TravelLayer = (function(_super) {
    __extends(TravelLayer, _super);

    function TravelLayer() {
      return TravelLayer.__super__.constructor.apply(this, arguments);
    }

    TravelLayer.prototype.initMap = function(map) {
      var photo, point, spot, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _results;
      if (map) {
        this.map = map;
      }
      this.calcSpotTime();
      point = [];
      if (this.travel) {
        _ref = this.travel.spots;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          spot = _ref[_i];
          _ref1 = spot.photos;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            photo = _ref1[_j];
            this.createMarker(photo);
          }
          point = [];
          _ref2 = spot.photos;
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            photo = _ref2[_k];
            point.push(this.createPoint(photo));
          }
          _results.push(spot.polyline = new AMap.Polyline({
            map: this.map,
            path: point,
            strokeWeight: 2
          }));
        }
        return _results;
      }
    };

    TravelLayer.prototype.createPoint = function(photo) {
      return new AMap.LngLat(photo.point.lng, photo.point.lat);
    };

    TravelLayer.prototype.createMarker = function(photo) {
      var marker, that;
      that = this;
      marker = new AMap.Marker({
        map: this.map,
        position: new AMap.LngLat(photo.point.lng, photo.point.lat),
        offset: new AMap.Pixel(-15, -15),
        content: this.getLabelContent(photo.oss_key),
        topWhenClick: true
      });
      marker.photo = photo;
      if (this.opts.clickable) {
        AMap.event.addListener(marker, 'click', function() {
          return jQuery(that).trigger("data_clicked", [this.photo.id]);
        });
      }
      photo.marker = marker;
      return marker;
    };

    TravelLayer.prototype.removeMarker = function(photo) {
      if (photo.marker) {
        photo.marker.setMap(null);
        return delete photo.marker;
      }
    };

    TravelLayer.prototype.toggleSpotLine = function(spot, visible) {
      if (spot.polyline) {
        if (visible) {
          return spot.polyline.show();
        } else {
          return spot.polyline.hide();
        }
      }
    };

    TravelLayer.prototype.setSpotEditable = function(spot, editable) {
      var editMarker, photo, that, _i, _len, _ref, _results;
      editable = !!editable;
      that = this;
      editMarker = function(marker) {
        if (marker) {
          marker.setDraggable(editable);
          if (that.opts.editable && editable) {
            return marker.dragListener = AMap.event.addListener(marker, 'dragend', function(e) {
              if (!this.photo.oPoint) {
                this.photo.oPoint = $.extend({}, this.photo.point);
              }
              this.photo.point.lat = e.lnglat.getLat();
              this.photo.point.lng = e.lnglat.getLng();
              that.updateSpotLine(spot);
              return $(that).trigger("spot.edited", [spot.id]);
            });
          } else if (marker.dragListener) {
            AMap.event.removeListener(marker.dragListener);
            return marker.dragListener = null;
          }
        }
      };
      if (this.opts.editable) {
        _ref = spot.photos;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          photo = _ref[_i];
          _results.push(editMarker(photo.marker));
        }
        return _results;
      }
    };

    TravelLayer.prototype.cancelSpotEdit = function(spot) {
      var cancelMarker, photo, _i, _len, _ref;
      cancelMarker = function(photo) {
        if (photo.oPoint) {
          photo.point = photo.oPoint;
          delete photo.oPoint;
        }
        if (photo.marker) {
          return photo.marker.setPosition(new AMap.LngLat(photo.point.lng, photo.point.lat));
        }
      };
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cancelMarker(photo);
      }
      return this.updateSpotLine(spot);
    };

    TravelLayer.prototype.updateSpotLine = function(spot) {
      var photo, point, _i, _len, _ref;
      point = [];
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        point.push(this.createPoint(photo));
      }
      if (spot.polyline) {
        return spot.polyline.setPath(point);
      } else {
        return spot.polyline = new AMap.Polyline({
          map: this.map,
          path: point,
          strokeWeight: 2
        });
      }
    };

    TravelLayer.prototype.createSpot = function(spot) {
      var cdistance, distance, photo, _i, _len, _ref;
      distance = 0;
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cdistance = window.cnmap.GPS.distanceInMeter(spot.center_lat, spot.center_lng, photo.point.lat, photo.point.lng);
        if (cdistance > distance) {
          distance = cdistance;
        }
      }
      return new AMap.Circle({
        map: this.map,
        center: new AMap.LngLat(spot.center_lng, spot.center_lat),
        radius: distance,
        strokeStyle: 'dashed',
        strokeColor: '#0066FF',
        strokeOpacity: 0.2,
        fillColor: '#0066FF',
        fillOpacity: 0.2
      });
    };

    return TravelLayer;

  })(window.cnmap.ITravelLayer);

  window.cnmap.TravelLayer = TravelLayer;

}).call(this);

//# sourceMappingURL=MapTravelImpl.map
