// Generated by CoffeeScript 1.8.0
(function() {
  var TravelLayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TravelLayer = (function(_super) {
    __extends(TravelLayer, _super);

    function TravelLayer() {
      return TravelLayer.__super__.constructor.apply(this, arguments);
    }

    TravelLayer.prototype.createPoint = function(photo) {
      return new AMap.LngLat(photo.point.lng, photo.point.lat);
    };

    TravelLayer.prototype.createMarker = function(photo) {
      var marker, that;
      that = this;
      marker = new AMap.Marker({
        map: this.map,
        position: new AMap.LngLat(photo.point.lng, photo.point.lat),
        offset: new AMap.Pixel(-15, -15),
        content: this.getLabelContent(photo.oss_key),
        topWhenClick: true
      });
      marker.photo = photo;
      if (this.opts.clickable) {
        AMap.event.addListener(marker, 'click', function() {
          return jQuery(that).trigger("data_clicked", [this.photo.id]);
        });
      }
      photo.marker = marker;
      return marker;
    };

    TravelLayer.prototype.createPolyline = function(points) {
      return new AMap.Polyline({
        map: this.map,
        path: points,
        strokeWeight: 2
      });
    };

    TravelLayer.prototype.setPolylinePath = function(polyline, points) {
      return polyline.setPath(points);
    };

    TravelLayer.prototype.removeMarker = function(photo) {
      if (photo.marker) {
        photo.marker.setMap(null);
        return delete photo.marker;
      }
    };

    TravelLayer.prototype.toggleSpotLine = function(spot, visible) {
      if (spot.polyline) {
        if (visible) {
          return spot.polyline.show();
        } else {
          return spot.polyline.hide();
        }
      }
    };

    TravelLayer.prototype.spotEditable = function(spot, editable) {
      var editMarker, photo, that, _i, _len, _ref, _results;
      editable = !!editable;
      that = this;
      editMarker = function(marker) {
        if (marker) {
          marker.setDraggable(that.opts.editable && editable);
          if (that.opts.editable && editable) {
            return marker.dragListener = AMap.event.addListener(marker, 'dragend', function(e) {
              if (!this.photo.oPoint) {
                this.photo.oPoint = $.extend({}, this.photo.point);
              }
              this.photo.point.lat = e.lnglat.getLat();
              this.photo.point.lng = e.lnglat.getLng();
              that.updateSpotLine(spot);
              return $(that).trigger("spot.edited", [spot.id]);
            });
          } else if (marker.dragListener) {
            AMap.event.removeListener(marker.dragListener);
            return marker.dragListener = null;
          }
        }
      };
      _ref = spot.photos;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        _results.push(editMarker(photo.marker));
      }
      return _results;
    };

    TravelLayer.prototype.cancelSpotEdit = function(spot) {
      var cancelMarker, photo, _i, _len, _ref;
      cancelMarker = function(photo) {
        if (photo.oPoint) {
          photo.point = photo.oPoint;
          delete photo.oPoint;
        }
        if (photo.marker) {
          return photo.marker.setPosition(new AMap.LngLat(photo.point.lng, photo.point.lat));
        }
      };
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cancelMarker(photo);
      }
      return this.updateSpotLine(spot);
    };

    TravelLayer.prototype.createSpot = function(spot) {
      var cdistance, distance, photo, _i, _len, _ref;
      distance = 0;
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cdistance = window.cnmap.GPS.distanceInMeter(spot.center_lat, spot.center_lng, photo.point.lat, photo.point.lng);
        if (cdistance > distance) {
          distance = cdistance;
        }
      }
      return new AMap.Circle({
        map: this.map,
        center: new AMap.LngLat(spot.center_lng, spot.center_lat),
        radius: distance,
        strokeStyle: 'dashed',
        strokeColor: '#0066FF',
        strokeOpacity: 0.2,
        fillColor: '#0066FF',
        fillOpacity: 0.2
      });
    };

    return TravelLayer;

  })(window.cnmap.ITravelLayer);

  window.cnmap.TravelLayer = TravelLayer;

}).call(this);

//# sourceMappingURL=MapTravelImpl.js.map
