// Generated by CoffeeScript 1.7.1
(function() {
  var IMapEvent;

  IMapEvent = (function() {
    function IMapEvent() {}

    IMapEvent.prototype.trigger = function(instance, eventName) {};

    return IMapEvent;

  })();

  window.ponm = window.ponm || {};

  window.ponm.IMapEvent = IMapEvent;

}).call(this);

//# sourceMappingURL=MapEvent.map
