// Generated by CoffeeScript 1.8.0
(function() {
  var IMapEventListener;

  IMapEventListener = (function() {
    function IMapEventListener() {}

    IMapEventListener.prototype.opts = {
      map: null
    };

    IMapEventListener.prototype.addLocationHashListener = function(map, callback) {};

    IMapEventListener.prototype.removeListener = function(listeners) {};

    IMapEventListener.prototype.addToolBar = function(map) {};

    IMapEventListener.prototype.setCenter = function(map, lat, lng) {};

    IMapEventListener.prototype.setZoom = function(map, zoom) {};

    IMapEventListener.prototype.setZoomAndCenter = function(map, zoom, lat, lng) {};

    IMapEventListener.prototype.zoomIn = function(map) {};

    IMapEventListener.prototype.zoomOut = function(map) {};

    IMapEventListener.prototype.setBounds = function(map, sw, ne) {};

    IMapEventListener.prototype.clearMap = function(map) {};

    IMapEventListener.prototype.inMapView = function(lat, lng, map) {};

    IMapEventListener.prototype.pixelToPoint = function(map, pixel) {};

    IMapEventListener.prototype.pointToPixel = function(map, point) {};

    IMapEventListener.prototype.addMarker = function(map, lat, lng) {};

    IMapEventListener.prototype.createDraggableMarker = function(map, lat, lng) {};

    IMapEventListener.prototype.activeMarker = function(marker) {};

    IMapEventListener.prototype.deactiveMarker = function(marker) {};

    IMapEventListener.prototype.addMarkerActiveListener = function(marker, callback) {};

    IMapEventListener.prototype.addDragendListener = function(marker, callback) {};

    IMapEventListener.prototype.removeMarker = function(marker) {};

    IMapEventListener.prototype.addMapClickListener = function(map, callback) {};

    IMapEventListener.prototype.setPosition = function(target, lat, lng) {};

    IMapEventListener.prototype.setMap = function(target, map) {};

    return IMapEventListener;

  })();

  window.cnmap = window.cnmap || {};

  window.cnmap.IMapEventListener = IMapEventListener;

}).call(this);

//# sourceMappingURL=MapEventListener.js.map
