// Generated by CoffeeScript 1.7.1
(function() {
  var IMapService;

  IMapService = (function() {
    function IMapService() {}

    IMapService.prototype.map = void 0;

    IMapService.prototype.init = function(map, callback) {};

    IMapService.prototype.getAddress = function(lat, lng, callback) {};

    IMapService.prototype.getAddrPois = function(lat, lng, callback) {};

    IMapService.prototype.getLocation = function(address, callback) {};

    IMapService.prototype.getLocPois = function(address, callback) {};

    return IMapService;

  })();

  window.cnmap = window.cnmap || {};

  window.cnmap.IMapService = IMapService;

}).call(this);

//# sourceMappingURL=MapService.map
