// Generated by CoffeeScript 1.7.1
(function() {
  var ITravelLayer, _ref;

  ITravelLayer = (function() {
    function ITravelLayer(opts) {
      var _ref;
      this.opts = opts;
      if (this.opts) {
        _ref = this.opts, this.ctx = _ref.ctx, this.map = _ref.map, this.travel = _ref.travel;
      }
      this.mapEventListener = window.cnmap.MapEventListener.factory();
      this.marker = this.createMarker();
    }

    ITravelLayer.prototype.initMap = function() {};

    ITravelLayer.prototype.setMap = function(map) {
      if (map) {
        this.map = map;
        return this.initMap();
      }
    };

    ITravelLayer.prototype.setTravel = function(travel) {
      var spot, _i, _len, _ref, _results;
      this.travel = travel;
      this.travel.spots.sort(function(a, b) {
        return a.id - b.id;
      });
      _ref = this.travel.spots;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        spot = _ref[_i];
        _results.push(spot.photos.sort(function(a, b) {
          return a.date_time - b.date_time;
        }));
      }
      return _results;
    };

    ITravelLayer.prototype.createLabel = function(photo) {};

    ITravelLayer.prototype.getLabelContent = function(photoId) {
      return "<img src='" + this.ctx + "/api/rest/photo/" + photoId + "/3' style='border: 2px solid white; width: 34px; height: 34px;'>";
    };

    ITravelLayer.prototype.activePhoto = function(photo) {
      if (!this.mapEventListener.inMapView(photo.point.lat, photo.point.lng, this.map)) {
        this.mapEventListener.setPosition(this.marker, photo.point.lat, photo.point.lng);
        this.mapEventListener.setCenter(this.map, photo.point.lat, photo.point.lng);
        return this.mapEventListener.setZoom(this.map, 18);
      } else {
        this.mapEventListener.setPosition(this.marker, photo.point.lat, photo.point.lng);
        return this.mapEventListener.setCenter(this.map, photo.point.lat, photo.point.lng);
      }
    };

    ITravelLayer.prototype.createMarker = function() {};

    ITravelLayer.prototype.activeSpot = function(spot) {
      var ne, photo, sw, _i, _len, _ref;
      if (spot.photos[0]) {
        sw = jQuery.extend({}, spot.photos[0].point);
      }
      if (spot.photos[1]) {
        if (spot.photos[1].point.lat < sw.lat || spot.photos[1].point.lng < sw.lng) {
          ne = sw;
          sw = jQuery.extend({}, spot.photos[1].point);
        } else {
          ne = jQuery.extend({}, spot.photos[1].point);
        }
      }
      if (sw && ne) {
        _ref = spot.photos;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          photo = _ref[_i];
          if (photo.point.lat < sw.lat) {
            sw.lat = photo.point.lat;
          }
          if (photo.point.lng < sw.lng) {
            sw.lng = photo.point.lng;
          }
          if (photo.point.lat > ne.lat) {
            ne.lat = photo.point.lat;
          }
          if (photo.point.lng > ne.lng) {
            ne.lng = photo.point.lng;
          }
        }
        return this.mapEventListener.setBounds(this.map, sw, ne);
      }
    };

    return ITravelLayer;

  })();

  window.cnmap = (_ref = window.cnmap) != null ? _ref : {};

  window.cnmap.ITravelLayer = ITravelLayer;

}).call(this);

//# sourceMappingURL=MapTravel.map
