// Generated by CoffeeScript 1.7.1
(function() {
  var distanceInMeter, _ref, _ref1;

  distanceInMeter = function(lat1, lng1, lat2, lng2) {
    var e, f, g, h;
    e = Math.PI * lat1 / 180;
    f = Math.PI * lng1 / 180;
    g = Math.PI * lat2 / 180;
    h = Math.PI * lng2 / 180;
    return 1000 * 6371 * Math.acos(Math.min(Math.cos(e) * Math.cos(g) * Math.cos(f) * Math.cos(h) + Math.cos(e) * Math.sin(f) * Math.cos(g) * Math.sin(h) + Math.sin(e) * Math.sin(g), 1));
  };

  window.cnmap = (_ref = window.cnmap) != null ? _ref : {};

  window.cnmap.GPS = (_ref1 = window.cnmap.GPS) != null ? _ref1 : {};

  window.cnmap.GPS.distanceInMeter = distanceInMeter;

}).call(this);

//# sourceMappingURL=MapUtils.map
