// Generated by CoffeeScript 1.8.0
(function() {
  var load_script, translate;

  load_script = function(xyUrl, callback) {
    var head, script;
    head = document.getElementsByTagName('head')[0];
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = xyUrl;
    script.onload = script.onreadystatechange = function() {
      if (!this.readyState || this.readyState === "loaded" || this.readyState === "complete") {
        callback && callback();
        script.onload = script.onreadystatechange = null;
        if (head && script.parentNode) {
          return head.removeChild(script);
        }
      }
    };
    return head.insertBefore(script, head.firstChild);
  };

  translate = function(point, type, callback) {
    var callbackName, xyUrl;
    callbackName = 'cbk_' + Math.round(Math.random() * 10000);
    xyUrl = "http://api.map.baidu.com/ag/coord/convert?from=" + type + "&to=4&x=" + point.lng + "&y=" + point.lat + "&callback=BMap.Convertor." + callbackName;
    load_script(xyUrl);
    return BMap.Convertor[callbackName] = function(xyResult) {
      delete BMap.Convertor[callbackName];
      point = new BMap.Point(xyResult.x, xyResult.y);
      return callback && callback(point);
    };
  };

  window.BMap = window.BMap || {};

  BMap.Convertor = {};

  BMap.Convertor.translate = translate;

}).call(this);

//# sourceMappingURL=MapConvertor.js.map
