// Generated by CoffeeScript 1.7.1
(function() {
  var $window, BMap, MapService,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $window = window;

  BMap = $window.BMap;

  MapService = (function(_super) {
    __extends(MapService, _super);

    function MapService(map) {
      this.map = map;
    }

    MapService.prototype.init = function(map, callback) {
      this.geocoder = new BMap.Geocoder();
      return callback.apply(this.geocoder, [this.geocoder]);
    };

    MapService.prototype.getAddress = function(lat, lng, callback) {
      if (!this.geocoder) {
        this.init();
      }
      return this.geocoder.getLocation(new BMap.Point(lng, lat), function(result) {
        if (result) {
          return callback.apply(void 0, [result.address]);
        }
      });
    };

    MapService.prototype.getLocation = function(address, callback) {
      if (!this.geocoder) {
        this.init();
      }
      return this.geocoder.getPoint(address, function(point) {
        if (point) {
          return callback.apply(void 0, [point]);
        }
      });
    };

    return MapService;

  })(window.cnmap.IMapService);

}).call(this);

//# sourceMappingURL=MapServiceImpl.map
