// Generated by CoffeeScript 1.7.1
(function() {
  var TravelLayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TravelLayer = (function(_super) {
    __extends(TravelLayer, _super);

    function TravelLayer() {
      return TravelLayer.__super__.constructor.apply(this, arguments);
    }

    TravelLayer.prototype.initMap = function(map) {
      var photo, point, spot, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _results;
      if (map) {
        this.map = map;
      }
      this.calcSpotTime();
      point = [];
      if (this.travel) {
        _ref = this.travel.spots;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          spot = _ref[_i];
          _ref1 = spot.photos;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            photo = _ref1[_j];
            this.createMarker(photo);
          }
          point = [];
          _ref2 = spot.photos;
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            photo = _ref2[_k];
            point.push(this.createPoint(photo));
          }
          spot.polyline = new BMap.Polyline(point, {
            map: this.map,
            strokeWeight: 2
          });
          _results.push(this.map.addOverlay(spot.polyline));
        }
        return _results;
      }
    };

    TravelLayer.prototype.createPoint = function(photo) {
      return new BMap.Point(photo.point.lng, photo.point.lat);
    };

    TravelLayer.prototype.createMarker = function(photo) {
      var marker, that;
      that = this;
      marker = new BMap.Marker(this.createPoint(photo), {
        icon: new BMap.Icon(this.getMarkerImage(photo), {
          width: 34,
          height: 34
        }),
        title: photo.title || ''
      });
      marker.photo = photo;
      this.map.addOverlay(marker);
      if (this.opts.clickable) {
        marker.addEventListener('click', function(e) {
          return jQuery(that).trigger("data_clicked", [this.photo.id]);
        });
      }
      photo.marker = marker;
      return marker;
    };

    TravelLayer.prototype.removeMarker = function(photo) {
      if (photo.marker) {
        this.map.removeOverlay(photo.marker);
        return delete photo.marker;
      }
    };

    TravelLayer.prototype.toggleSpotLine = function(spot, visible) {
      if (spot.polyline) {
        if (visible) {
          return spot.polyline.show();
        } else {
          return spot.polyline.hide();
        }
      }
    };

    TravelLayer.prototype.setSpotEditable = function(spot, editable) {
      var editMarker, photo, that, _i, _len, _ref, _results;
      editable = !!editable;
      that = this;
      editMarker = function(marker) {
        if (marker) {
          if (editable) {
            marker.enableDragging();
          } else {
            marker.disableDragging();
          }
          if (that.opts.editable && editable) {
            return marker.addEventListener('dragend', function(e) {
              if (!this.photo.oPoint) {
                this.photo.oPoint = $.extend({}, this.photo.point);
              }
              this.photo.point.lat = e.point.lat;
              this.photo.point.lng = e.point.lng;
              that.updateSpotLine(spot);
              return $(that).trigger("spot.edited", [spot.id]);
            });
          } else {
            return marker.removeEventListener('dragend');
          }
        }
      };
      if (this.opts.editable) {
        _ref = spot.photos;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          photo = _ref[_i];
          _results.push(editMarker(photo.marker));
        }
        return _results;
      }
    };

    TravelLayer.prototype.cancelSpotEdit = function(spot) {
      var cancelMarker, photo, that, _i, _len, _ref;
      that = this;
      cancelMarker = function(photo) {
        if (photo.oPoint) {
          photo.point = photo.oPoint;
          delete photo.oPoint;
        }
        if (photo.marker) {
          return photo.marker.setPosition(that.createPoint(photo));
        }
      };
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cancelMarker(photo);
      }
      return this.updateSpotLine(spot);
    };

    TravelLayer.prototype.updateSpotLine = function(spot) {
      var photo, point, _i, _len, _ref;
      point = [];
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        point.push(this.createPoint(photo));
      }
      if (spot.polyline) {
        return spot.polyline.setPath(point);
      } else {
        spot.polyline = new BMap.Polyline(point, {
          map: this.map,
          strokeStyle: 'dashed'
        });
        return this.map.addOverlay(spot.polyline);
      }
    };

    return TravelLayer;

  })(window.cnmap.ITravelLayer);

  window.cnmap.TravelLayer = TravelLayer;

}).call(this);

//# sourceMappingURL=MapTravelImpl.map
