// Generated by CoffeeScript 1.8.0
(function() {
  var TravelLayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TravelLayer = (function(_super) {
    __extends(TravelLayer, _super);

    function TravelLayer() {
      return TravelLayer.__super__.constructor.apply(this, arguments);
    }

    TravelLayer.prototype.createPoint = function(photo) {
      return new BMap.Point(photo.point.lng, photo.point.lat);
    };

    TravelLayer.prototype.createMarker = function(photo) {
      var marker, that;
      if (!photo.point) {
        return;
      }
      that = this;
      marker = new BMap.Marker(this.createPoint(photo), {
        icon: new BMap.Icon(this.getMarkerImage(photo), {
          width: 34,
          height: 34
        }),
        title: photo.title || ''
      });
      marker.photo = photo;
      this.map.addOverlay(marker);
      if (this.opts.clickable) {
        marker.addEventListener('click', function(e) {
          return jQuery(that).trigger("data_clicked", [this.photo.id]);
        });
      }
      photo.marker = marker;
      return marker;
    };

    TravelLayer.prototype.createPolyline = function(points) {
      var polyline;
      polyline = new BMap.Polyline(points, {
        map: this.map,
        strokeWeight: 2
      });
      this.map.addOverlay(polyline);
      return polyline;
    };

    TravelLayer.prototype.setPolylinePath = function(polyline, points) {
      return polyline.setPath(points);
    };

    TravelLayer.prototype.removeMarker = function(photo) {
      if (photo.marker) {
        this.map.removeOverlay(photo.marker);
        return delete photo.marker;
      }
    };

    TravelLayer.prototype.toggleSpotLine = function(spot, visible) {
      if (spot.polyline) {
        if (visible) {
          return spot.polyline.show();
        } else {
          return spot.polyline.hide();
        }
      }
    };

    TravelLayer.prototype.spotEditable = function(spot, editable) {
      var editMarker, photo, that, _i, _len, _ref, _results;
      editable = !!editable;
      that = this;
      editMarker = function(marker) {
        if (marker) {
          if (that.opts.editable && editable) {
            marker.enableDragging();
          } else {
            marker.disableDragging();
          }
          if (that.opts.editable && editable) {
            return marker.addEventListener('dragend', function(e) {
              if (!this.photo.oPoint) {
                this.photo.oPoint = $.extend({}, this.photo.point);
              }
              this.photo.point.lat = e.point.lat;
              this.photo.point.lng = e.point.lng;
              that.updateSpotLine(spot);
              return $(that).trigger("spot.edited", [spot.id]);
            });
          } else {
            return marker.removeEventListener('dragend');
          }
        }
      };
      _ref = spot.photos;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        _results.push(editMarker(photo.marker));
      }
      return _results;
    };

    TravelLayer.prototype.cancelSpotEdit = function(spot) {
      var cancelMarker, photo, that, _i, _len, _ref;
      that = this;
      cancelMarker = function(photo) {
        if (photo.oPoint) {
          photo.point = photo.oPoint;
          delete photo.oPoint;
        }
        if (photo.marker) {
          return photo.marker.setPosition(that.createPoint(photo));
        }
      };
      _ref = spot.photos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        photo = _ref[_i];
        cancelMarker(photo);
      }
      return this.updateSpotLine(spot);
    };

    return TravelLayer;

  })(window.cnmap.ITravelLayer);

  window.cnmap.TravelLayer = TravelLayer;

}).call(this);

//# sourceMappingURL=MapTravelImpl.js.map
